name: Build and Deploy
on:
    push:
        branches: [main]

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: npm i
            - name: Build project
              run: npm run build
            - name: Archieve static website
              uses: actions/upload-artifact@v3
              with:
                  name: builddir
                  path: ./dist

    deploy:
        name: deploy
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - uses: actions/checkout@v3
            - name: Download math result for job 1
              uses: actions/download-artifact@v3
              with:
                  name: builddir
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist/kanban
